server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://mongo1:123456@10.130.213.163:27017/TKFINANCE?authMechanism=SCRAM-SHA-1
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 10.130.217.180
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      lettuce:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 1000
filePath:
  relativePath: /api/**
  uploadPath: /usr/local/taibao/
##客户端接口地址
clientUrl: http://10.130.213.159:8080/axis2/services/TKNewsService
##客户端数据配置
nMaxNum: 300
nMaxDepth: 10
nOrderType: 0
flWeightThreshold: 0