server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://finance:pass1234@10.130.218.166:27017/TKfinance?authMechanism=SCRAM-SHA-1
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 10.130.218.167
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      lettuce:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 1000
filePath:
  relativePath: /api/**
  uploadPath: /usr/local/taibao/
##客户端接口地址
clientUrl: http://10.130.218.175:8080/axis2/services/TKNewsService
#quantClientUrl: http://10.130.218.175:8080/axis2/services/TKQuantizationService
##客户端数据配置
nMaxNum: 300
nMaxDepth: 10
nOrderType: 0
flWeightThreshold: 0

fillterKeyWords: 上市公司股票,股转系统股票,其他公司

quant:
  stocklist: quant_stocklist
  correlation: _correlation
  multidays: _multidays
  oneday: _oneday